#!/bin/sh
VERSION=`egrep AM_INIT_AUTOMAKE configure.in | sed -e 's/^.*,//' -e 's/).*$//'`
echo "Building nickle $VERSION RPM..." >&2
cvs -r export -D now -d nickle-$VERSION nickle
(cd nickle-$VERSION && sh ./autoconfigure.sh)
chmod +w nickle-$VERSION/nickle.spec
ed nickle-$VERSION/nickle.spec << EOF
g/VERSION/s/VERSION/$VERSION/
w
q
EOF
chmod -w nickle-$VERSION/nickle.spec
tar cf - nickle-$VERSION | bzip2 > nickle-$VERSION.tar.gz 
rm -rf nickle-$VERSION
rpm -ta --clean nickle-$VERSION.tar.bz2
