/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header$
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <unistd.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 90
#define YY_END_OF_BUFFER 91
static yyconst short int yy_accept[245] =
    {   0,
        0,    0,   91,   89,   80,   46,   79,   59,   89,   60,
       43,   58,   62,   89,   47,   48,   55,   53,   42,   54,
       44,   56,   83,   86,   78,   41,   71,   66,   72,   77,
       88,   49,   50,   61,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       51,   63,   52,   65,    2,   70,    0,   82,    0,   75,
        0,    0,   67,   68,   45,   87,    0,    1,   57,   87,
       83,   86,    0,    0,    0,   73,   69,   74,   88,   64,
       88,   88,   88,   88,   88,   88,   18,   88,   88,   88,
       88,   88,   88,   88,   19,   88,   88,   88,   88,   88,

       88,   88,   88,   88,   88,   88,   88,   88,   88,   76,
       82,   81,   81,    0,   87,    0,    0,   87,   84,   85,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   17,   88,   88,   88,   88,   26,   88,   88,   88,
       88,   88,   88,   32,   88,   88,   88,   88,   88,   24,
       88,   88,   87,    0,   88,    3,   88,   88,   88,   88,
       88,   11,   20,   88,    9,   36,   34,   88,   88,   88,
       88,   88,   88,   88,    8,   88,   14,   88,   88,   88,
       88,   88,   88,   88,   88,   31,   21,   25,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   13,   88,

       88,   88,   37,   10,   88,   88,   88,   88,   16,   88,
       88,   29,   88,   88,    4,   88,   38,   88,   88,   40,
       88,   23,    5,   30,   33,   88,   88,   15,   88,   88,
       12,   27,   88,   88,   88,   22,   88,    6,   88,   28,
        7,   39,   35,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       22,   22,   22,   22,   22,   23,   23,   24,   25,   26,
       27,   28,   29,    1,   30,   30,   30,   30,   31,   30,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       33,   34,   35,   36,   37,    1,   38,   39,   40,   41,

       42,   43,   44,   45,   46,   32,   47,   48,   49,   50,
       51,   52,   53,   54,   55,   56,   57,   32,   58,   59,
       60,   32,   61,   62,   63,   64,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[65] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    3,
        3,    3,    3,    1,    1,    1,    1,    1,    1,    3,
        3,    4,    1,    1,    1,    1,    4,    3,    3,    3,
        3,    3,    3,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        1,    1,    1,    1
    } ;

static yyconst short int yy_base[249] =
    {   0,
        0,  336,  342,  344,  344,  344,  344,  314,   59,  344,
      344,  344,  330,  305,  344,  344,  344,  323,  344,   49,
       47,   57,   60,   67,  344,  344,  310,  309,  308,  344,
        0,  344,  344,  298,   18,  279,   35,   50,   55,   43,
      284,  285,   61,   61,  273,   75,   39,  275,  278,  282,
      344,  264,  344,  344,  344,  344,   91,  344,   99,  344,
      314,  313,  344,  344,  344,  100,  106,  344,  344,  114,
      126,  132,  149,   86,    0,  344,  344,  344,    0,  344,
      269,  266,  279,  264,  269,  275,  260,  270,  260,   84,
      260,  263,  261,  256,    0,  258,  253,  260,  261,  267,

      259,  248,  122,  252,  260,   78,  241,  259,  253,  344,
      133,  344,  287,  159,  163,  167,  175,  179,  120,    0,
      259,  245,  257,  254,  237,  254,  252,  234,  247,  246,
      231,  239,  245,  245,  227,  231,  239,  220,  229,  230,
      221,  230,  234,    0,  217,  221,  224,  215,  105,    0,
      228,  221,  161,  186,  208,    0,  220,  221,  219,  207,
      215,    0,    0,  210,    0,    0,  205,  222,  204,  197,
      204,  198,  190,  199,    0,  193,    0,  189,  200,  193,
      194,  189,  198,  194,  194,    0,    0,    0,  185,  186,
      191,  176,  185,  182,  175,  172,  185,  175,    0,  185,

      173,  171,    0,    0,  180,  175,  162,  171,    0,  159,
      159,    0,  168,  162,    0,  152,    0,  157,  156,    0,
      166,    0,    0,    0,    0,  143,  149,    0,  126,  126,
        0,    0,  121,  111,  116,    0,   93,    0,   93,    0,
        0,    0,    0,  344,  249,  253,  255,   71
    } ;

static yyconst short int yy_def[249] =
    {   0,
      244,    1,  244,  244,  244,  244,  244,  244,  245,  244,
      244,  244,  244,  246,  244,  244,  244,  244,  244,  244,
      244,  244,  244,  244,  244,  244,  244,  244,  244,  244,
      247,  244,  244,  244,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      244,  244,  244,  244,  244,  244,  245,  244,  245,  244,
      244,  246,  244,  244,  244,  244,  244,  244,  244,  244,
      244,  244,  244,  244,  248,  244,  244,  244,  247,  244,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,

      247,  247,  247,  247,  247,  247,  247,  247,  247,  244,
      245,  244,  244,  244,  244,  244,  244,  244,  244,  248,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  244,  244,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,

      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,    0,  244,  244,  244,  244
    } ;

static yyconst short int yy_nxt[409] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   24,   24,   25,   26,   27,   28,   29,   30,   31,
       31,   31,   32,    4,   33,   34,    4,   35,   36,   37,
       38,   39,   40,   41,   42,   43,   31,   31,   31,   31,
       31,   44,   45,   46,   47,   48,   49,   50,   31,   31,
       51,   52,   53,   54,   58,   64,   66,   66,   66,   66,
       68,   81,   84,  120,   82,   69,   65,   70,  104,   71,
       71,   71,   72,  105,   70,   85,   72,   72,   72,   72,
       73,   86,   59,   91,  106,   88,   58,   73,   74,   92,

       87,   73,   89,   95,  111,  119,  119,   67,   73,   96,
       97,   98,  102,   90,   99,  148,  103,  100,   75,   66,
       66,   66,   66,  130,   59,  114,  114,  114,  114,  131,
       73,  149,   59,  115,  115,  115,  115,  243,   58,  119,
      119,   73,  242,   70,   73,   71,   71,   71,   72,   70,
      182,   72,   72,   72,   72,   73,   73,  241,  240,  143,
       67,  183,   73,  117,  144,  117,   59,   73,  118,  118,
      118,  118,  239,   73,  116,  238,  237,  145,  114,  114,
      114,  114,  115,  115,  115,  115,  154,  154,  154,  154,
      236,   73,  235,   73,  118,  118,  118,  118,  118,  118,

      118,  118,   73,  234,   73,  154,  154,  154,  154,  233,
      232,  231,  230,  229,  228,  227,  226,  225,  224,  223,
      222,  153,  221,  116,  220,  219,  218,  217,  216,  215,
      214,  213,  212,  211,  210,  209,  208,  207,  206,  205,
      204,  203,  202,  201,  200,  199,  198,  197,  153,   57,
      196,   57,   57,   61,  195,   61,   61,   79,   79,  194,
      193,  192,  191,  190,  189,  188,  187,  186,  185,  184,
      181,  180,  179,  178,  177,  176,  175,  174,  173,  172,
      171,  170,  169,  168,  167,  166,  165,  164,  163,  162,
      161,  160,  159,  158,  157,  156,  155,  112,  152,  151,

      150,  147,  146,  142,  141,  140,  139,  138,  137,  136,
      135,  134,  133,  132,  129,  128,  127,  126,  125,  124,
      123,  122,  121,  113,  112,  110,  109,  108,  107,  101,
       94,   93,   83,   80,   78,   77,   76,   63,   62,   60,
       56,  244,   55,    3,  244,  244,  244,  244,  244,  244,
      244,  244,  244,  244,  244,  244,  244,  244,  244,  244,
      244,  244,  244,  244,  244,  244,  244,  244,  244,  244,
      244,  244,  244,  244,  244,  244,  244,  244,  244,  244,
      244,  244,  244,  244,  244,  244,  244,  244,  244,  244,
      244,  244,  244,  244,  244,  244,  244,  244,  244,  244,

      244,  244,  244,  244,  244,  244,  244,  244
    } ;

static yyconst short int yy_chk[409] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    9,   20,   21,   21,   21,   21,
       22,   35,   37,  248,   35,   22,   20,   23,   47,   23,
       23,   23,   23,   47,   24,   37,   24,   24,   24,   24,
       23,   38,    9,   40,   47,   39,   57,   24,   23,   40,

       38,   23,   39,   43,   59,   74,   74,   21,   24,   43,
       43,   44,   46,   39,   44,  106,   46,   44,   23,   66,
       66,   66,   66,   90,   57,   67,   67,   67,   67,   90,
       66,  106,   59,   70,   70,   70,   70,  239,  111,  119,
      119,   66,  237,   71,   70,   71,   71,   71,   71,   72,
      149,   72,   72,   72,   72,   70,   71,  235,  234,  103,
       66,  149,   72,   73,  103,   73,  111,   71,   73,   73,
       73,   73,  233,   72,   70,  230,  229,  103,  114,  114,
      114,  114,  115,  115,  115,  115,  116,  116,  116,  116,
      227,  153,  226,  115,  117,  117,  117,  117,  118,  118,

      118,  118,  153,  221,  115,  154,  154,  154,  154,  219,
      218,  216,  214,  213,  211,  210,  208,  207,  206,  205,
      202,  114,  201,  115,  200,  198,  197,  196,  195,  194,
      193,  192,  191,  190,  189,  185,  184,  183,  182,  181,
      180,  179,  178,  176,  174,  173,  172,  171,  154,  245,
      170,  245,  245,  246,  169,  246,  246,  247,  247,  168,
      167,  164,  161,  160,  159,  158,  157,  155,  152,  151,
      148,  147,  146,  145,  143,  142,  141,  140,  139,  138,
      137,  136,  135,  134,  133,  132,  131,  130,  129,  128,
      127,  126,  125,  124,  123,  122,  121,  113,  109,  108,

      107,  105,  104,  102,  101,  100,   99,   98,   97,   96,
       94,   93,   92,   91,   89,   88,   87,   86,   85,   84,
       83,   82,   81,   62,   61,   52,   50,   49,   48,   45,
       42,   41,   36,   34,   29,   28,   27,   18,   14,   13,
        8,    3,    2,  244,  244,  244,  244,  244,  244,  244,
      244,  244,  244,  244,  244,  244,  244,  244,  244,  244,
      244,  244,  244,  244,  244,  244,  244,  244,  244,  244,
      244,  244,  244,  244,  244,  244,  244,  244,  244,  244,
      244,  244,  244,  244,  244,  244,  244,  244,  244,  244,
      244,  244,  244,  244,  244,  244,  244,  244,  244,  244,

      244,  244,  244,  244,  244,  244,  244,  244
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lex.l"
#define INITIAL 0
#line 2 "lex.l"
/* $Header$ */

/*
 * Copyright (C) 1988-2001 Keith Packard and Bart Massey.
 * All Rights Reserved.  See the file COPYING in this directory
 * for licensing information.
 */

#include	<config.h>

#include	"nickle.h"
#include	"gram.h"
#include	<strings.h>
#include	<errno.h>

int	    at_bol = True;
int	    yylineno;
    
#undef YY_INPUT

#define YY_INPUT(buf,result,max_size) \
{ \
    int c; \
    result = 0; \
    if (at_bol) yyprompt (); \
    while (result < max_size) { \
	c = FileInput (yyinput); \
	at_bol = False; \
	if (c < 0) { \
	    c = popinput (); \
	    if (c < 0) \
		break; \
	} \
	buf[result++] = c; \
	if (c == '\n') \
	{ \
	    at_bol = True; \
	    yylineno++; \
	    break; \
	} \
    } \
}
    
#ifndef FLEX_SCANNER
#undef		input
#undef		unput
int input (void)
{
    char    buf[1];
    int	    r;

    YY_INPUT(buf, r, 1);
    if (r == 0)
	return 0;
    return buf[0];
}

void unput (char c)
{
    if (c == '\n')
	yylineno--;
    FileUnput (yyinput, c);
}
#endif

#define		YYINDEEP	20
Value	yyinstack[YYINDEEP];
Value	*yyinpt = yyinstack + YYINDEEP;
Value	yyinput;
int		linenos[YYINDEEP];
int		*linenopt = linenos + YYINDEEP;
char		*yyfile = "";
char		*fnames[YYINDEEP];
char		**fnamept = fnames + YYINDEEP;
int		yyfiledeep = 0;

#line 612 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp = NULL, *yy_bp = NULL;
	register int yy_act;

#line 79 "lex.l"

#line 768 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 245 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 344 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 80 "lex.l"
skipcomment();
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 81 "lex.l"
skipline();
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 82 "lex.l"
{ yylval.cval = class_auto; return AUTO; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 83 "lex.l"
{ yylval.cval = class_global; return GLOBAL; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 84 "lex.l"
{ yylval.cval = class_static; return STATIC; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 85 "lex.l"
{ yylval.tval = type_func; return FUNCTION; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 86 "lex.l"
{ return UNDEFINE; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 87 "lex.l"
return QUIT;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 88 "lex.l"
return QUIT;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 89 "lex.l"
return SHELL;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 90 "lex.l"
return EDIT;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 91 "lex.l"
return HISTORY;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 92 "lex.l"
return PRINT;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 93 "lex.l"
return READ;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 94 "lex.l"
return DEFAULT;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 95 "lex.l"
{ yylval.ival = WHILE; return WHILE; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 96 "lex.l"
{ yylval.ival = FOR; return FOR; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 97 "lex.l"
{ yylval.ival = DO; return DO; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 98 "lex.l"
{ yylval.ival = IF; return IF; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 99 "lex.l"
{ yylval.ival = ELSE; return ELSE; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 100 "lex.l"
{ yylval.ival = BREAK; return BREAK; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 101 "lex.l"
{ yylval.ival = CONTINUE; return CONTINUE; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 102 "lex.l"
{ yylval.ival = RETURNTOK; return RETURNTOK; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 103 "lex.l"
{ yylval.ival = TRY; return TRY; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 104 "lex.l"
{ yylval.ival = CATCH; return CATCH; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 105 "lex.l"
{ yylval.tval = type_int; return INT; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 106 "lex.l"
{ yylval.tval = type_integer; return INTEGER; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 107 "lex.l"
{ yylval.tval = type_rational; return RATIONAL; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 108 "lex.l"
{ yylval.tval = type_double; return DOUBLE; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 109 "lex.l"
{ yylval.tval = type_string; return STRING; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 110 "lex.l"
{ yylval.tval = type_array; return ARRAY; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 111 "lex.l"
{ yylval.tval = type_ref; return REF; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 112 "lex.l"
{ yylval.tval = type_struct; return STRUCT; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 113 "lex.l"
{ yylval.tval = type_func; return FUNC; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 114 "lex.l"
{ yylval.tval = type_undef; return POLYMORPH; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 115 "lex.l"
{ yylval.ival = FORK; return FORK; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 116 "lex.l"
{ yylval.ival = SCOPE; return SCOPE; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 117 "lex.l"
{ yylval.ival = IMPORT; return IMPORT; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 118 "lex.l"
{ yylval.ival = EXCEPTION; return EXCEPTION; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 119 "lex.l"
{ yylval.pval = publish_public; return PUBLIC; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 120 "lex.l"
{ yylval.ival = SEMI; return SEMI; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 121 "lex.l"
{ yylval.ival = COMMA; return COMMA; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 122 "lex.l"
{ yylval.ival = DOLLAR; return DOLLAR; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 123 "lex.l"
{ yylval.ival = DOT; return DOT; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 124 "lex.l"
{ yylval.ival = ARROW; return ARROW; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 125 "lex.l"
{ if (!ignorenl) { yylval.ival = NL; return NL; } }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 126 "lex.l"
{ yylval.ival = OP; return OP; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 127 "lex.l"
{ yylval.ival = CP; return CP; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 128 "lex.l"
{ yylval.ival = OS; return OS; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 129 "lex.l"
{ yylval.ival = CS; return CS; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 130 "lex.l"
{ yylval.ival = OC; return OC; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 131 "lex.l"
{ yylval.ival = CC; return CC; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 132 "lex.l"
{ yylval.ival = PLUS; return PLUS; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 133 "lex.l"
{ yylval.ival = MINUS; return MINUS; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 134 "lex.l"
{ yylval.ival = TIMES; return TIMES; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 135 "lex.l"
{ yylval.ival = DIVIDE; return DIVIDE; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 136 "lex.l"
{ yylval.ival = DIV; return DIV; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 137 "lex.l"
{ yylval.ival = MOD; return MOD; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 138 "lex.l"
{ yylval.ival = BANG; return BANG; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 139 "lex.l"
{ yylval.ival = POUND; return POUND; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 140 "lex.l"
{ yylval.ival = POW; return POW; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 141 "lex.l"
{ yylval.ival = LAND; return LAND; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 142 "lex.l"
{ yylval.ival = LOR; return LOR; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 143 "lex.l"
{ yylval.ival = LXOR; return LXOR; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 144 "lex.l"
{ yylval.ival = LNOT; return LNOT; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 145 "lex.l"
{ yylval.ival = ASSIGN; return ASSIGN; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 146 "lex.l"
{ yylval.ival = INC; return INC; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 147 "lex.l"
{ yylval.ival = DEC; return DEC; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 148 "lex.l"
{ yylval.ival = EQ; return EQ; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 149 "lex.l"
{ yylval.ival = NE; return NE; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 150 "lex.l"
{ yylval.ival = LT; return LT; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 151 "lex.l"
{ yylval.ival = GT; return GT; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 152 "lex.l"
{ yylval.ival = LE; return LE; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 153 "lex.l"
{ yylval.ival = GE; return GE; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 154 "lex.l"
{ yylval.ival = AND; return AND; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 155 "lex.l"
{ yylval.ival = OR; return OR; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 156 "lex.l"
{ yylval.ival = QUEST; return QUEST; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 157 "lex.l"
{ yylval.ival = COLON; return COLON; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 158 "lex.l"
;
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 159 "lex.l"
;
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 160 "lex.l"
{   ENTER ();
		    int	i;
		    
		    if (yytext[1] == '\\')
			i = lexEscape (yytext[2]);
		    else
			i = yytext[1];
		    yylval.vval = NewInt (i);
		    EXIT ();
		    REFERENCE (yylval.vval);
		    return CONST;
		}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 172 "lex.l"
{
			ENTER ();
			register char	*c, *s;
    			yytext[yyleng - 1] = '\0';
			yylval.vval = NewString (yyleng-2);
			c = StringChars (&yylval.vval->string);
			s = yytext + 1;
			while (*s) {
				if (*s == '\\')
					*c++ = lexEscape (*++s);
				else
					*c++ = *s;
				++s;
			}
			*c = '\0';
			EXIT ();
			REFERENCE (yylval.vval);
			return CONST;
		}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 191 "lex.l"
{
		yylval.vval = atov(yytext+1, 8);
		return CONST;
		}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 195 "lex.l"
{
		yylval.vval = atov(yytext+2, 2);
		return CONST;
		}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 199 "lex.l"
{
		yylval.vval = atov(yytext+2, 16);
		return CONST;
		}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 203 "lex.l"
{
		yylval.vval = atov(yytext, 10);
		return CONST;
		}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 207 "lex.l"
{
		yylval.vval = aetov (yytext);
		return CONST;
		}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 211 "lex.l"
{
		yylval.aval = AtomId (yytext);
		return NAME;
		}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 215 "lex.l"
FilePrintf (FileStderr, "character \\%o ignored\n", *yytext & 0xff);
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 216 "lex.l"
ECHO;
	YY_BREAK
#line 1349 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 245 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 245 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 244);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}



#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 216 "lex.l"


int
lexEscape (int c)
{
    switch (c) {
    case '0':
	return '\0';
	break;
    case 'b':
	return '\b';
	break;
    case 'n':
	return '\n';
	break;
    case 't':
	return '\t';
	break;
    case 'f':
	return '\f';
	break;
    default:
	return c;
    }
}

void
skipcomment (void)
{
    int	c;

    c = input();
    for (;;) {
	while (c != EOF && c != '*')
	    c = input();
	if (c == EOF)
	    return;
	c = input();
	if (c == EOF || c == '/')
	    return;
    }
}

void
skipline (void)
{
    int	    c;

    do {
	c = input();
    } while (c != EOF && c != '\n');
}

Value
atov (char *s, int base)
{
    ENTER ();
    Value	result;
    Value	d, b;

    b = NewInt (base);
    result = NewInt (0);
    for (;;) {
	switch (*s) {
	case '0': case '1': case '2': case '3': case '4':
	case '5': case '6': case '7': case '8': case '9':
	    d = NewInt (*s - '0');
	    break;
	case 'a': case 'b': case 'c': case 'd': case 'e': case 'f':
	    d = NewInt (*s - 'a' + 10);
	    break;
	case 'A': case 'B': case 'C': case 'D': case 'E': case 'F':
	    d = NewInt (*s - 'A' + 10);
	    break;
	default:
	    RETURN (result);
	}
	if (d->ints.value >= base)
	    break;
	result = Plus (d, Times (result, b));
	++s;
    }
    RETURN (result);
}

Value
aetov (char *s)
{
    ENTER ();
    char    *int_part, *frac_part, *rep_part, *exp_part, *next;
    int	    sign, frac_len, rep_len, esign;
    Value   v, sv;

    int_part = s;
    sign = 1;
    if (*int_part == '+')
	int_part++;
    else if (*int_part == '-') {
	int_part++;
	sign = -1;
    }
    next = int_part;
    frac_part = strchr (next, '.');
    frac_len = -1;
    rep_part = 0;
    rep_len = 0;
    esign = 1;
    if (frac_part) {
	frac_part++;
	next = frac_part;
	rep_part = strchr (next, '{');
	if (rep_part)
	{
	    frac_len = rep_part - frac_part;
	    rep_part++;
	    next = strchr (rep_part, '}');
	    if (!next)
		RETURN (Zero);	    /* "can't" happen */
	    rep_len = next - rep_part;
	    next = next + 1;
	}
    }
    exp_part = strchr (next, 'e');
    if (!exp_part)
	exp_part = strchr (next, 'E');
    if (exp_part) {
	if (frac_len < 0)
	    frac_len = exp_part - frac_part;
	exp_part++;
	if (*exp_part == '+')
	    exp_part++;
	else if (*exp_part == '-') {
	    esign = -1;
	    exp_part++;
	}
    } else if (frac_len < 0)
	frac_len = strlen(frac_part);
    v = atov (int_part, 10);
    if (frac_part && frac_len)
    {
	v = Plus (v, Divide (atov (frac_part, 10),
				 Pow (NewInt (10),
				       NewInt (frac_len))));
    }
    if (rep_part)
    {
	Value	rep;
	
	rep = Divide (atov (rep_part, 10), Minus (Pow (NewInt (10),
						       NewInt (rep_len)),
						  One));
	if (frac_len)
	    rep = Divide (rep, Pow (NewInt (10),
				    NewInt (frac_len)));
	v = Plus (v, rep);
    }
    if (exp_part) 
    {
	sv = Pow (NewInt (10), atov (exp_part, 10));
	if (esign > 0)
	    v = Times (v, sv);
	else
	    v = Divide (v, sv);
    }
    RETURN (v);
}

Bool
lexfile(char *s)
{
    Value	f;
    f = FileFopen (s, "r");
    interactive = 0;
    if (f == 0) {
	FilePuts (FileStderr, "cannot open file \"");
	FilePuts (FileStderr, s);
	FilePuts (FileStderr, "\"\n");
	return False;
    }
    ++yyfiledeep;
    yyinput = f;
    yyfile = s;
    return True;
}

void
lexstdin(void)
{
    --yyfiledeep;
    (void) FileClose (yyinput);
    yyinput = FileStdin;
    interactive = stdin_interactive;
}
	
Bool
pushinput (char *s, Bool complain)
{
    Value	f;

    if (yyinpt == yyinstack) {
	(void) FilePrintf (FileStderr, "files nested too deeply\n");
	return False;
    }
    f = FileFopen (s, "r");
    if (f == 0) {
	if (complain)
	    (void) FilePrintf (FileStderr, "cannot open file %s\n", s);
	return False;
    }
    ++yyfiledeep;
    *--yyinpt = yyinput;
    *--linenopt = yylineno;
    *--fnamept = yyfile;
    yyinput = f;
    yylineno = 1;
    yyfile = s;
    interactive = 0;
    return True;
}

int
popinput (void)
{
    int	    c;

/*    printf ("popinput\n"); */
    for (;;)
    {
	c = FileInput (yyinput);
	if (c >= 0)
	    return c;
	if (c == FileBlocked)
	    ThreadsRun (0, yyinput);
	else
	{
	    FileClose (yyinput);
	    if (yyinpt == yyinstack + YYINDEEP)
		return FileEOF;
	    yyinput = *yyinpt++;
	    if (yyinput == FileStdin)
	    {
		interactive = stdin_interactive;
		yyprompt ();
	    }
	    yylineno = *linenopt++;
	    yyfile = *fnamept++;
	    --yyfiledeep;
	}
    }
}

void
yyprompt (void)
{
    ENTER ();
    Value	v;
    
    if (interactive)
    {
	if (ignorenl)
	    v = lookupVar ("prompt2");
	else if (CurrentFrame)
	    v = lookupVar ("prompt3");
	else
	    v = lookupVar ("prompt");
	dofformat (FileStdout, "%s", 1, &v);
	FileFlush (FileStdout);
    }
    EXIT ();
}

