.\" $Header$
.TH IC 1 "3 May 1988"
.SH NAME
ic \- a polymorphic desk calculator
.SH SYNOPSIS
ic [ file ... ]
.SH DESCRIPTION
\fIIc\fP is an interpreter for a simple language which is quite easy to use
as a desk calculator.  \fIIc\fP supports several datatypes, int, natural,
integer, ratio, double, string and array.  natural, integer and ratio are
implemented with arbitrary precision.  \fIIc\fP can automatically convert
between types when appropriate.
.PP
The input language vaguely resembles C.  Some things in C which don't
translate easily are different, and some features are simply missing
(like \fIop\fP\fB=\fP constructions).  To make the input language more
useful in an interactive setting, \fBnewline\fP only terminates
statements at ``reasonable'' times.  \fBNewline\fP terminates either
expressions or single statements typed by the user, inside compound
statements or function definitions, only a \fB;\fP terminates.  This should
not cause any problems, it usually stays out of the way.
.PP
The syntax for \fIic\fP programs is as follows; name means
a sequence of letters, digits and _ not starting with a digit; E means
expression; S means statement.  arrays are any expression which results
in an array.

.LP
Comments are enclosed in /* and */

.LP
operands
.IP
floating point numbers - can include exponent, need not
include decimal point nor sign.
.IP
octal numbers - start with a 0, eg 014 is the same as 12.
.IP
hexdecimal numbers - start with "0x", eg 0x1a is the same as 26.
.IP
name
.IP
name (E) - a function call.
.LP
Operators.  These are in order of decreasing precedence.
.IP "(type) E"
cast the result of E into this type
.IP "array [E]"
refers to the E'th element of this array
.IP "++ --"
Increment/Decrement - either postfix or prefix.
.IP "-"
Unary negate
.IP "! E"
Logical negation.
.IP "E !"
Factorial.
.IP "^"
Exponentiation
.IP "* / %"
Times, divide and remainder
.IP "+ -"
Addition and subtraction.
.IP "<= >= < >"
Relational operators.
.IP "== !="
Equality operators.
.IP "|| &&"
Logical OR and AND.
.IP "E ? E : E"
.IP "="
Assignment
.IP "[E1]([E2]...)"
creates an array with E1 elements (each containing an array of E2 elements ...).
For example, to make "a" reference a 10x10 array, "a = [10][10]".
.LP
Statement forms.
.IP "E;"
Evaluates the expression.
.IP "{S ... S}"
Executes the enclosed statements in order.
.IP "if (E) S"
.IP "if (E) S then S"
.IP "while (E) S"
.IP "do S while (E);"
.IP "for (opt-E; opt-E; opt-E) S"
.IP ";"
The null statement
.IP "break;"
Discontinue execution of the nearest enclosing for/do/while statement.
.IP "continue;"
Branch directly to the conditional test of the nearest enclosing
for/do/while statement.
.IP "return E;"
.LP
\fIIc\fP supports polymorphic data -- as an expresion is evaluated, the
resultant data type is picked to fit the data.  Variables and arrays can be
typed so that data which will not fit in them will be flagged as an error.
Polymorphic variables/functions do not place restrictions on the assigned
data type and is the default type for all objects.  The different types are
described below
.IP "polymorph"
This describes the union of all datatypes.  A variable with this type
can contain any data value.
.IP "int"
32 bit signed integers.  Lean and mean, they can be quite limiting.
.IP "natural"
Arbitrary precision natural numbers (i.e. non-negative integers).
.IP "integer"
Arbitrary precision integers.  Simply natural numbers with a sign
flag.
.IP "ratio"
Arbitrary precision rational numbers.  Simply an integer numerator and a
natural denominator.
.IP "double"
Double precision floating point numbers.  As many computations cannot
be carried out exactly as rational numbers, \fIic\fP implements non-precise
arithmetic using normal machine-specific floating point numbers.  A better
solution would be to compute functional representations of the numbers
(e.g. sqrt(2) / sin (30) instead of 2.828427).  But this is less frequently
useful than the speed offered by the hardware solution.
.IP "string"
A regular array of characters.  The \fB+\fP operator concatenates strings
together.
.IP "array"
A collection of any data.  Arrays have a type associated with them.  When
data is stored into the array, it is first coerced into the associated type.
.IP "file"
A file is a stdio file pointer.  You can't do much with it except pass it
to builtin functions.
.LP
Variables also have scope.  Global variables are persistant and can be
referenced by any function in the system.  Auto variables are transitory,
existing only while the enclosing function is executing.  Static variables
are persistant, but only availible to the enclosing function.  The default
for names created at the top level is "global", the default for local
variables is "auto".  
.nf
	global
	static
	auto
.fi
.LP
Functions are defined like the following:
.nf
	function [type] name ([type] name, ... , [type] name)
	{
		[type and/or class] name, name;
		...
		
		S ...
	}
.fi
.LP
The type of the function is optional, by default it is "polymorph".  The
variables declared inside the function body can be either "auto" or
"static".  Auto is the default.
.LP
\fIIc\fP has a collection of standard functions built in.  The math functions
are implemented with routines from the C library, for their behaviour,
please consult the appropriate manuals.
.IP
abs, acos, asin, atan, atan2, ceil, cos, cosh, exp, fclose, fflush, floor,
fopen, fprintf, hypot, j0, j1, jn, log, log10, printf, scanf, sin, sinh,
sqrt, tan, tanh, y0, y1, yn
.IP	
Note: trig functions take and return arguments in
degrees - not radians!
.IP	
Fprintf and Printf accept a reasonable sub-set of the stdio
library version:  %d, %e, %c, %g, %f, %s, %o work
as expected.
.LP
There are several other miscelaneous commands availible:
.IP "quit"
exit ic
.IP "default <type>"
specifies a default type for expressions.  With a default type, each
function that is sumarily created, or each expression typed in at the
top level will have all computations done with this type.
.IP "undefine name {,name}"
removes these names from the system.  If you have accidentally
redefined a builtin function, you can "undefine" the new definition and
recover the old.
.IP "read \"file\""
read commands from a file.  
.IP "expr1 # expr2"
print expr1 in base expr2
.IP "print name"
If name is a function, display a formatted version of the function.
Comments and original formating are lost.  If name is a variable, print the
current type and value of the variable.
.IP "edit function or edit file-name"
Invokes $EDITOR on the named function, or the named file.  In the second
form, any expression with a string value is acceptable.
.IP "history"
Displays the 10 most recently printed values.  They can be accessed
with \fB$\fP\fIn\fP where \fIn\fP is the number displayed to the
right of the value in this list.
.IP "history= \fIboolean-value\fP"
Specifies whether the history index of printed values should be displayed 
when the value is first printed.
.IP "history \fIn\fP,\fIm\fP"
Displays history values n through m.
.LP
All function arguments are passed by value except for arrays which
are always passed by reference.

For example (taken from the \fIbc\fP manual:

.nf
function exponent(double x)
{
	double	a, b, c, i, s;
	
	a = 1;
	b = 1;
	s = 1;
	for (i = 1;; i++) {
		a = a * x;
		b = b * i;
		c = a/b;
		if (abs(c) < 1e-6 == 0)
			return s;
		s = s + c;
	}
}
.fi
defines a function to compute an approximate value of the exponential
function and

.nf
	for (i = 1; i < 10; i++)
		printf ("%g\\n", exponent (i));
.fi

prints approximate values of the exponential function of the first
ten integers.
.SH BUGS
.PP
Conversion between ratio and double types is effected by converting both the
numerator and denominator to double and simply dividing.  This can lead to
problems when neither is expressable as a double.
.SH AUTHOR
\fIIc\fP was written by Keith Packard; keith@expo.lcs.mit.edu.
.PP
This file is Copyright (C) 1988 by Keith Packard.  IC is provided to
you without charge, and with no warranty.  You may give away copies of
IC, including source, provided that this notice is included in all the
files.
